<?php
/**
 * Plugin container
 *
 * PHP Version 5.3
 *
 * @category  Accounts
 * @package   Auth
 * @author    Victor Nițu <victor@serenitymedia.ro>
 * @copyright 2010 Serenity Media
 * @license   http://www.gnu.org/licenses/agpl-3.0.txt AGPLv3
 * @link      http://docs.serenitymedia.ro
 */

/**
 * authFacebook
 * Facebook authentication plugin.
 *
 * @category  Accounts
 * @package   Auth
 * @author    Victor Nițu <victor@serenitymedia.ro>
 * @copyright 2010 Serenity Media
 * @license   http://www.gnu.org/licenses/agpl-3.0.txt AGPLv3
 * @link      http://docs.serenitymedia.ro
 */

class AuthFacebook extends AuthCommon implements AuthModel
{

    /**
     * __construct
     *
     * @access public
     * @return void
     */
    public function __construct()
    {
        //
    }
}
?>
